tvar simplemaps_worldmap_mapdata={
  main_settings: {
   //General settings
    width: "responsive", //'700' or 'responsive'
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#ffffff",
    popups: "detect",
    
    //State defaults
    state_description: "State description",
    state_color: "#88A4BC",
    state_hover_color: "#3B729F",
    state_url: "http://simplemaps.com",
    border_size: 1.5,
    all_states_inactive: "no",
    all_states_zoomable: "no",
    
    //Location defaults
    location_description: "Location description",
    location_color: "#FF0067",
    location_opacity: 0.8,
    location_hover_opacity: 1,
    location_url: "",
    location_size: 25,
    location_type: "square",
    location_image_source: "frog.png",
    location_border_color: "#FFFFFF",
    location_border: 2,
    location_hover_border: 2.5,
    all_locations_inactive: "no",
    all_locations_hidden: "no",
    
    //Label defaults
    label_color: "#d5ddec",
    label_hover_color: "#d5ddec",
    label_size: 22,
    label_font: "Arial",
    hide_labels: "no",
   
    //Zoom settings
    zoom: "yes",
    back_image: "no",
    initial_back: "no",
    initial_zoom: -1,
    initial_zoom_solo: "no",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.5,
    
    //Popup settings
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "12px/1.5 Verdana, Arial, Helvetica, sans-serif",
    popup_nocss: "no",
    
    //Advanced settings
    div: "map",
    auto_load: "yes",
    url_new_tab: "yes",
    images_directory: "default",
    fade_time: 0.1,
    link_text: "View Website",
    state_image_url: "",
    state_image_position: "",
    location_image_url: ""
  },
  state_specific: {
    AF: {},
    AO: {},
    AL: {},
    AE: {},
    AR: {},
    AM: {},
    AU: {},
    AT: {},
    AZ: {},
    BI: {},
    BE: {},
    BJ: {},
    BF: {},
    BD: {},
    BG: {},
    BH: {},
    BA: {},
    BY: {},
    BZ: {},
    BO: {},
    BR: {},
    BN: {},
    BT: {},
    BW: {},
    CF: {},
    CA: {},
    CH: {},
    CL: {},
    CN: {},
    CI: {},
    CM: {},
    CD: {},
    CG: {},
    CO: {},
    CR: {},
    CU: {},
    CZ: {},
    DE: {},
    DJ: {},
    DK: {},
    DO: {},
    DZ: {},
    EC: {},
    EG: {},
    ER: {},
    EE: {},
    ET: {},
    FI: {},
    FJ: {},
    GA: {},
    GB: {},
    GE: {},
    GH: {},
    GN: {},
    GM: {},
    GW: {},
    GQ: {},
    GR: {},
    GL: {},
    GT: {},
    GY: {},
    HN: {},
    HR: {},
    HT: {},
    HU: {},
    ID: {},
    IN: {},
    IE: {},
    IR: {},
    IQ: {},
    IS: {},
    IL: {},
    IT: {},
    JM: {},
    JO: {},
    JP: {},
    KZ: {},
    KE: {},
    KG: {},
    KH: {},
    KR: {},
    XK: {},
    KW: {},
    LA: {},
    LB: {},
    LR: {},
    LY: {},
    LK: {},
    LS: {},
    LT: {},
    LU: {},
    LV: {},
    MA: {},
    MD: {},
    MG: {},
    MX: {},
    MK: {},
    ML: {},
    MM: {},
    ME: {},
    MN: {},
    MZ: {},
    MR: {},
    MW: {},
    MY: {},
    NA: {},
    NE: {},
    NG: {},
    NI: {},
    NL: {},
    NO: {},
    NP: {},
    NZ: {},
    OM: {},
    PK: {},
    PA: {},
    PE: {},
    PH: {},
    PG: {},
    PL: {},
    KP: {},
    PT: {},
    PY: {},
    PS: {},
    QA: {},
    RO: {},
    RU: {},
    RW: {},
    EH: {},
    SA: {},
    SD: {},
    SS: {},
    SN: {},
    SL: {},
    SV: {},
    RS: {},
    SR: {},
    SK: {},
    SI: {},
    SE: {},
    SZ: {},
    SY: {},
    TD: {},
    TG: {},
    TH: {},
    TJ: {},
    TM: {},
    TL: {},
    TN: {},
    TR: {},
    TW: {},
    TZ: {},
    UG: {},
    UA: {},
    UY: {},
    US: {},
    UZ: {},
    VE: {},
    VN: {},
    VU: {},
    YE: {},
    ZA: {},
    ZM: {},
    ZW: {},
    SO: {},
    GF: {},
    FR: {},
    ES: {},
    AW: {},
    AI: {},
    AD: {},
    AG: {},
    BS: {},
    BM: {},
    BB: {},
    KM: {},
    CV: {},
    KY: {},
    DM: {},
    FK: {},
    FO: {},
    GD: {},
    HK: {},
    KN: {},
    LC: {},
    LI: {},
    MF: {},
    MV: {},
    MT: {},
    MS: {},
    MU: {},
    NC: {},
    NR: {},
    PN: {},
    PR: {},
    PF: {},
    SG: {},
    SB: {},
    ST: {},
    SX: {},
    SC: {},
    TC: {},
    TO: {},
    TT: {},
    VC: {},
    VG: {},
    VI: {},
    CY: {},
    RE: {},
    YT: {},
    MQ: {},
    GP: {},
    CW: {},
    IC: {}
  },
  locations: {},
  labels: {},
  legend: {
    entries: []
  },
  regions: {
    "0": {
      name: "North America",
      states: [
        "MX",
        "CA",
        "US",
        "GL",
        "BM"
      ]
    },
    "1": {
      name: "South America",
      states: [
        "EC",
        "AR",
        "VE",
        "BR",
        "CO",
        "BO",
        "PE",
        "BZ",
        "CL",
        "CR",
        "CU",
        "DO",
        "SV",
        "GT",
        "GY",
        "GF",
        "HN",
        "NI",
        "PA",
        "PY",
        "PR",
        "SR",
        "UY",
        "JM",
        "HT",
        "BS",
        "FK",
        "AI",
        "AG",
        "AW",
        "BB",
        "VG",
        "KY",
        "DM",
        "MQ",
        "LC",
        "VC",
        "GD",
        "GP",
        "MS",
        "TC",
        "SX",
        "MF",
        "KN",
        "CW"
      ]
    },
    "2": {
      name: "Europe",
      states: [
        "IT",
        "NL",
        "NO",
        "DK",
        "IE",
        "GB",
        "RO",
        "DE",
        "FR",
        "AL",
        "AM",
        "AT",
        "BY",
        "BE",
        "LU",
        "BG",
        "CZ",
        "EE",
        "GE",
        "GR",
        "HU",
        "IS",
        "LV",
        "LT",
        "MD",
        "PL",
        "PT",
        "RS",
        "SI",
        "HR",
        "BA",
        "ME",
        "MK",
        "SK",
        "ES",
        "FI",
        "SE",
        "CH",
        "TR",
        "CY",
        "UA",
        "XK",
        "MT",
        "FO"
      ]
    },
    "3": {
      name: "Africa and the Middle East",
      states: [
        "QA",
        "BH",
        "SA",
        "AE",
        "SY",
        "OM",
        "KW",
        "PK",
        "AZ",
        "AF",
        "IR",
        "IQ",
        "IL",
        "PS",
        "JO",
        "LB",
        "YE",
        "TJ",
        "TM",
        "UZ",
        "KG",
        "NE",
        "AO",
        "EG",
        "TN",
        "GA",
        "DZ",
        "LY",
        "CG",
        "GQ",
        "BJ",
        "BW",
        "BF",
        "BI",
        "CM",
        "CF",
        "TD",
        "CI",
        "CD",
        "DJ",
        "ET",
        "GM",
        "GH",
        "GN",
        "GW",
        "KE",
        "LS",
        "LR",
        "MG",
        "MW",
        "ML",
        "MA",
        "MR",
        "MZ",
        "NA",
        "NG",
        "ER",
        "RW",
        "SN",
        "SL",
        "SO",
        "ZA",
        "SD",
        "SS",
        "SZ",
        "TZ",
        "TG",
        "UG",
        "EH",
        "ZM",
        "ZW",
        "RE",
        "KM",
        "SC",
        "MU",
        "CV",
        "IC",
        "ST",
        "YT"
      ]
    },
    "4": {
      name: "South Asia",
      states: [
        "SG",
        "TW",
        "IN",
        "AU",
        "MY",
        "NP",
        "NZ",
        "TH",
        "BN",
        "JP",
        "VN",
        "LK",
        "SB",
        "FJ",
        "BD",
        "BT",
        "KH",
        "LA",
        "MM",
        "KP",
        "PG",
        "PH",
        "KR",
        "ID",
        "CN",
        "MV",
        "NC",
        "VU",
        "NR"
      ]
    },
    "5": {
      name: "North Asia",
      states: [
        "MN",
        "RU",
        "KZ"
      ]
    }
  }
};